using System;
using System.Threading.Tasks;
using RestLess.Sample;
using RestLess.Sample.ConstantsNamespace;


// This file is generated by RestLess.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace RestLess.Generated
{
    internal sealed class RestClientForIRestApi01 : RestClientBase, IRestApi01
    {
        public Task<string> GetBook(string id)
        {
            return RestRequest.Get(this)
                              .WithUriTemplatePrefix(Constants.BaseApi)
                              .WithUriTemplate("/v1/app/books/{id}")
                              .WithUriVariable("id", id)
                              .ReadAsStringAsync();
        }

        public Task<string> GetBook2(string id)
        {
            return RestRequest.Get(this)
                              .WithUriTemplatePrefix(Constants.BaseApi)
                              .WithUriTemplate("/v1/app/books/{id}")
                              .WithUriVariable("id", id)
                              .ReadAsStringAsync();
        }
    }
}