using System;
using System.Threading.Tasks;
using DoLess.Rest.ConsoleSample;


// This file is generated by DoLess.Rest.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace DoLess.Rest.Generated
{
    internal sealed class RestClientForIGitHubApi : RestClientBase, IGitHubApi
    {
        public Task<User> GetUserAsync(string userId)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("users{/userId}")
                              .WithUriVariable("userId", userId)
                              .WithHeader("User-Agent", "DoLess.Rest")
                              .ReadAsObject<User>();
        }
    }
}