using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using DoLess.Rest.IntegrationTests.Entities;
using DoLess.Rest.IntegrationTests.Interfaces;


// This file is generated by DoLess.Rest.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace DoLess.Rest.Generated
{
    internal sealed class RestClientForIApi05 : RestClientBase, IApi05
    {
        public Task GetAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .SendAsync();
        }

        public Task<HttpResponseMessage> GetHttpResponseMessageAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<string> GetStringAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .ReadAsStringAsync();
        }

        public Task<byte[]> GetByteArrayAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .ReadAsByteArrayAsync();
        }

        public Task<Stream> GetStreamAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .ReadAsStreamAsync();
        }

        public Task<bool> GetBoolIsOkAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .SendAndGetSuccessAsync();
        }

        public Task<bool> GetBoolIsKoAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/ko")
                              .SendAndGetSuccessAsync();
        }

        public Task<Person> GetStudentAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/students/1")
                              .ReadAsObject<Person>();
        }
    }
}