using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using DoLess.Rest.IntegrationTests.Interfaces;


// This file is generated by DoLess.Rest.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace DoLess.Rest.Generated
{
    internal sealed class RestClientForIApi06 : RestClientBase, IApi06
    {
        public Task<HttpResponseMessage> GetInterfaceHeaderAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithHeader("X-DoLess", "Rest")
                              .WithHeader("X-DoLess-Scope", "Interface")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> GetMethodHeaderAsync()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithHeader("X-DoLess", "Rest")
                              .WithHeader("X-DoLess-Scope", "Interface")
                              .WithHeader("X-DoLess-Scope", "Method")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> GetParameterHeaderAsync(string header)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithHeader("X-DoLess", "Rest")
                              .WithHeader("X-DoLess-Scope", "Interface")
                              .WithHeader("X-DoLess-Scope", "Method")
                              .WithHeader("X-DoLess-Scope", header)
                              .ReadAsHttpResponseMessageAsync();
        }
    }
}