using System.Net.Http;
using System.Threading.Tasks;
using DoLess.Rest.IntegrationTests.Interfaces;

/*
* This file is generated by DoLess.Rest.
* All modifications will be erased at the next build.
* Please modify the dependent interface in order to change this file.
*/
namespace DoLess.Rest.Generated
{
    internal sealed class RestClientForIApi02WithoutBaseUrl : RestClientBase, IApi02WithoutBaseUrl
    {
        public Task<HttpResponseMessage> Get01Async()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> Get02Async()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("/api/posts")
                              .ReadAsHttpResponseMessageAsync();
        }
    }

    internal sealed class RestClientForIApi02WithBaseUrl01 : RestClientBase, IApi02WithBaseUrl01
    {
        public Task<HttpResponseMessage> Get01Async()
        {
            return RestRequest.Get(this)
                              .WithBaseUrl("api")
                              .WithUriTemplate("posts")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> Get02Async()
        {
            return RestRequest.Get(this)
                              .WithBaseUrl("api")
                              .WithUriTemplate("/posts")
                              .ReadAsHttpResponseMessageAsync();
        }
    }

    internal sealed class RestClientForIApi02WithBaseUrl02 : RestClientBase, IApi02WithBaseUrl02
    {
        public Task<HttpResponseMessage> Get01Async()
        {
            return RestRequest.Get(this)
                              .WithBaseUrl("/api")
                              .WithUriTemplate("posts")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> Get02Async()
        {
            return RestRequest.Get(this)
                              .WithBaseUrl("/api")
                              .WithUriTemplate("/posts")
                              .ReadAsHttpResponseMessageAsync();
        }
    }

    internal sealed class RestClientForIApi02WithBaseUrl03 : RestClientBase, IApi02WithBaseUrl03
    {
        public Task<HttpResponseMessage> Get01Async()
        {
            return RestRequest.Get(this)
                              .WithBaseUrl("/api/")
                              .WithUriTemplate("posts")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> Get02Async()
        {
            return RestRequest.Get(this)
                              .WithBaseUrl("/api/")
                              .WithUriTemplate("/posts")
                              .ReadAsHttpResponseMessageAsync();
        }
    }
}