using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using DoLess.Rest.IntegrationTests.Interfaces;


// This file is generated by DoLess.Rest.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace DoLess.Rest.Generated
{
    internal sealed class RestClientForIApi03 : RestClientBase, IApi03
    {
        public Task<HttpResponseMessage> GetCancellableAsync(CancellationToken cancellationToken = default)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .ReadAsHttpResponseMessageAsync(cancellationToken);
        }
    }
}