using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using RestLess.ConsoleSample.GitHub.V3;
using RestLess.ConsoleSample.GitHub.V3.Entities;


// This file is generated by RestLess.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace RestLess.Generated
{
    internal sealed class RestClientForIGitHubApi : RestClientBase, IGitHubApi
    {
        public Task<User> GetUserAsync(string username)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("/users{/username}")
                              .WithUriVariable("username", username)
                              .WithHeader("Accept", "application/vnd.github.v3+json")
                              .WithHeader("User-Agent", "RestLess Sample")
                              .ReadAsObject<User>();
        }

        public Task<IReadOnlyList<User>> GetOrganizationMembersAsync(string org, string filter = null, string role = null)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("/orgs{/org}/members{?filter,role}")
                              .WithUriVariable("org", org)
                              .WithUriVariable("filter", filter)
                              .WithUriVariable("role", role)
                              .WithHeader("Accept", "application/vnd.github.v3+json")
                              .WithHeader("User-Agent", "RestLess Sample")
                              .ReadAsObject<IReadOnlyList<User>>();
        }

        public Task<SearchResult<User>> FindUsersAsync(string query, string sort = null, string order = null)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("/search/users?q={+q}{&sort,order}")
                              .WithUriVariable("q", query)
                              .WithUriVariable("sort", sort)
                              .WithUriVariable("order", order)
                              .WithHeader("Accept", "application/vnd.github.v3+json")
                              .WithHeader("User-Agent", "RestLess Sample")
                              .ReadAsObject<SearchResult<User>>();
        }
    }
}