using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using RestLess.IntegrationTests.Interfaces;


// This file is generated by RestLess.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace RestLess.Generated
{
    internal sealed class RestClientForIApi03 : RestClientBase, IApi03
    {
        public Task<HttpResponseMessage> GetCancellableAsync(CancellationToken cancellationToken = default)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .ReadAsHttpResponseMessageAsync(cancellationToken);
        }

        public Task<HttpResponseMessage> GetWithFormatters()
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithMediaTypeFormatter("MediaTypeJsonFormatter")
                              .WithUrlParameterFormatter("UrlParameterFormatter")
                              .WithFormFormatter("FormFormatter")
                              .ReadAsHttpResponseMessageAsync();
        }
    }
}