using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using RestLess.IntegrationTests.Interfaces;


// This file is generated by RestLess.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace RestLess.Generated
{
    internal sealed class RestClientForIApi07 : RestClientBase, IApi07
    {
        public Task<HttpResponseMessage> GetUniqueContent01Async(string content)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithContent(content, "content")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> GetUniqueContent02Async(Dictionary<string, string> content)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithFormUrlEncodedContent(content)
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> GetMultipartContent01Async(FileInfo content)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithContent(content, "content")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> GetMultipartContent02Async(string content, string content2)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithContent(content, "content")
                              .WithContent(content2, "firstName")
                              .ReadAsHttpResponseMessageAsync();
        }

        public Task<HttpResponseMessage> GetMultipartContent03Async(string content, string content2)
        {
            return RestRequest.Get(this)
                              .WithUriTemplate("api/posts")
                              .WithContent(content, "content")
                              .WithContent(content2, "firstName", "f", "text/plain")
                              .ReadAsHttpResponseMessageAsync();
        }
    }
}