using System;
using System.Collections.Generic;
using System.Text;
using DoLess.Rest.ConsoleSample.TheMovieDb;


// This file is generated by DoLess.Rest.
// All modifications will be erased at the next build.
// Please modify the dependent interface in order to change this file.
namespace DoLess.Rest.Generated
{
    internal sealed class RestClientForITheMovieDbApi : RestClientBase, ITheMovieDbApi
    {
    }
}